In [2]:
import pandas as pd

sales = pd.read_csv('sales.csv', delimiter = '\t')
targets = pd.read_csv('targets.csv', delimiter = '\t')
men_women = pd.read_csv('men_women.csv')


display(sales)
display(targets)
display(men_women)

combined = sales.merge(targets).merge(men_women)
display(combined)


results = combined[(combined.revenue > combined.target) & (combined.women > combined.men)]
display(results)

      month  revenue
0   January      300
1  February      290
2     March      310
3     April      325
4       May      475
5      June      495

      month  target
0   January     310
1  February     270
2     March     300
3     April     350
4       May     475
5      June     500

      month  men  women
0   January   30     35
1  February   29     35
2     March   31     29
3     April   32     28
4       May   47     50
5      June   49     45

      month  revenue  target  men  women
0   January      300     310   30     35
1  February      290     270   29     35
2     March      310     300   31     29
3     April      325     350   32     28
4       May      475     475   47     50
5      June      495     500   49     45

      month  revenue  target  men  women
1  February      290     270   29     35

In [3]:
customers = pd.DataFrame({
    "customer_id": ["C01", "C02"],
    "customer_name": ["Alex Kim", "Jordan Lee"]
})

products = pd.DataFrame({
    "product_id": ["P10", "P12"],
    "product_name": ["Laptop", "Mouse"],
    "product_price": [999.99, 25.99]
})

orders = pd.DataFrame({
    "order_id": [101, 102, 103, 104],
    "customer_id": ["C01", "C01", "C02", "C01"],
    "product_id": ["P10", "P12", "P10", "P10"],
    "quantity": [1, 2, 1, 1]
})

# display(customers)
# display(products)
# display(orders)

full_orders = orders.merge(customers).merge(products)
display(full_orders)

customer_totals = full_orders.groupby("customer_name").apply(lambda x: (x.product_price * x.quantity).sum()).reset_index()

display(customer_totals)

,order_id,customer_id,product_id,quantity,customer_name,product_name,product_price
0,101,C01,P10,1,Alex Kim,Laptop,999.99
1,102,C01,P12,2,Alex Kim,Mouse,25.99
2,103,C02,P10,1,Jordan Lee,Laptop,999.99
3,104,C01,P10,1,Alex Kim,Laptop,999.99

C:\Users\PLUSKH01\AppData\Local\Temp\ipykernel_21232\853350815.py:26: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  customer_totals = full_orders.groupby("customer_name").apply(lambda x: (x.product_price * x.quantity).sum()).reset_index()

  customer_name        0
0      Alex Kim  2051.96
1    Jordan Lee   999.99

In [5]:
customers = pd.read_csv('customers.csv', delimiter = "\t")
products = pd.read_csv('products.csv', delimiter = "\t")
orders = pd.read_csv('orders.csv', delimiter = '\t')

# display(customers)
display(products)
display(orders)

products.rename(columns = {"id":"product_id"}, inplace = True)
product_orders = products.merge(orders)
display(product_orders)

   id         description  price
0   1      thing-a-ma-jig      5
1   2  whatcha-ma-call-it     10
2   3          doo-hickey      7
3   4               gizmo      3

   id  product_id  customer_id  quantity   timestamp
0   1           3            2         1  2017-01-01
1   2           2            2         3  2017-01-01
2   3           1            3         1  2017-01-01
3   4           2            3         2  2016-02-01
4   5           3            3         3  2017-02-01
5   6           4            1         2  2017-03-01
6   7           1            1         1  2017-02-02
7   8           4            1         1  2017-02-02

,product_id,description,price,id,customer_id,quantity,timestamp
0,1,thing-a-ma-jig,5,3,3,1,2017-01-01
1,1,thing-a-ma-jig,5,7,1,1,2017-02-02
2,2,whatcha-ma-call-it,10,2,2,3,2017-01-01
3,2,whatcha-ma-call-it,10,4,3,2,2016-02-01
4,3,doo-hickey,7,1,2,1,2017-01-01
5,3,doo-hickey,7,5,3,3,2017-02-01
6,4,gizmo,3,6,1,2,2017-03-01
7,4,gizmo,3,8,1,1,2017-02-02